# Generated by Django 2.2.4 on 2020-02-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='area_total',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='valor_imposto',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='valor_venal_total',
            field=models.DecimalField(decimal_places=2, default=21, max_digits=5),
            preserve_default=False,
        ),
    ]
