# Generated by Django 2.2.4 on 2020-02-08 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_auto_20200208_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='id_proprietario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contas.Clientes'),
        ),
    ]
