# Generated by Django 2.2.4 on 2020-02-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_auto_20200208_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='area_total',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='valor_imposto',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='valor_venal_total',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
