# Generated by Django 2.2.4 on 2020-02-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_auto_20200208_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='valor_imposto',
            field=models.DecimalField(decimal_places=9, max_digits=10, null=True),
        ),
    ]
