# Generated by Django 2.2.4 on 2020-02-09 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_auto_20200208_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='valor_imposto',
        ),
    ]
